# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 5, 13, 51, 26, 207165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 5, 13, 51, 26, 206164, tzinfo=utc)),
        ),
    ]
